### ISSUE TITLE
./gradlew assembleRelease BUILD FAILED

### ISSUE THREAD

**Issue by czhaoli** [Richard-Cao/react-native-exceptions-manager#1]
/Users/macbook/Documents/smartsport-school-frontend-app/node_modules/react-native-exceptions-manager/android/app/src/main/java/com/richardcao/exceptionsmanager/react/ExceptionsManager.java:17: 错误: ExceptionsManager不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()

**Comment by czhaoli** [comment]
react-native 0.41.2, react-native-exceptions-manager 1.0.9

**Comment by Richard-Cao** [comment]
报错的英文能看看吗？这个翻译感觉有点怪
https://github.com/Richard-Cao/react-native-exceptions-manager/blob/master/android/app/src/main/java/com/richardcao/exceptionsmanager/react/ExceptionsManager.java#L27
这里我加了注释

**Comment by czhaoli** [comment]
我用0.41.2的rn版本，把react-native-exceptions-manager改为1.0.8就能正常打包apk，如果是用1.0.9就会报错

**Comment by Richard-Cao** [comment]
那我知道了，是RN-Android的一个break change

**Comment by czhaoli** [comment]
嗯嗯，可以close了
